<?php

namespace App\Support\Planeacion\ProgramaTejido;

/**
 * Definición de las columnas de la grilla de Programa Tejido (orden, label y tipo de fecha).
 * Dato estático de UI: lo consumen la vista del controller, ProgramaTejidoBoard y
 * ProgramaTejidoReadService.
 */
final class ColumnasGrillaProgramaTejido
{
    /** @return list<array{field: string, label: string, dateType: string|null}> */
    public static function todas(): array
    {
        return [
            // Orden solicitado: todas visibles por ahora
            ['field' => 'EnProceso', 'label' => 'Estado', 'dateType' => null],
            ['field' => 'Reprogramar', 'label' => 'Reprogramar', 'dateType' => null],
            ['field' => 'CuentaRizo', 'label' => 'Cuenta', 'dateType' => null],
            ['field' => 'CalibreRizo2', 'label' => 'Calibre Rizo', 'dateType' => null],
            ['field' => 'SalonTejidoId', 'label' => 'Salón', 'dateType' => null],
            ['field' => 'NoTelarId', 'label' => 'Telar', 'dateType' => null],
            ['field' => 'Ultimo', 'label' => 'Último', 'dateType' => null],
            ['field' => 'CambioHilo', 'label' => 'C Hilo', 'dateType' => null],
            ['field' => 'Maquina', 'label' => 'Maq', 'dateType' => null],
            ['field' => 'Ancho', 'label' => 'Ancho', 'dateType' => null],
            ['field' => 'EficienciaSTD', 'label' => 'Ef Std', 'dateType' => null],
            ['field' => 'VelocidadSTD', 'label' => 'Vel', 'dateType' => null],
            ['field' => 'FibraRizo', 'label' => 'Hilo', 'dateType' => null],
            ['field' => 'CalibrePie2', 'label' => 'Calibre Pie', 'dateType' => null],
            ['field' => 'CalendarioId', 'label' => 'Jornada', 'dateType' => null],
            ['field' => 'TamanoClave', 'label' => 'Clave Mod.', 'dateType' => null],
            ['field' => 'NoExisteBase', 'label' => 'Usar cuando no existe en base', 'dateType' => null],
            ['field' => 'ItemId', 'label' => 'Clave AX', 'dateType' => null],
            ['field' => 'InventSizeId', 'label' => 'Tamaño AX', 'dateType' => null],
            ['field' => 'Rasurado', 'label' => 'Rasurado', 'dateType' => null],
            ['field' => 'NombreProducto', 'label' => 'Producto', 'dateType' => null],
            ['field' => 'TotalPedido', 'label' => 'Pedido', 'dateType' => null],
            ['field' => 'PorcentajeSegundos', 'label' => '% Segundas', 'dateType' => null],
            ['field' => 'Produccion', 'label' => 'Producción', 'dateType' => null],
            ['field' => 'SaldoPedido', 'label' => 'Saldos', 'dateType' => null],
            ['field' => 'SaldoMarbete', 'label' => 'Saldo Marbetes', 'dateType' => null],
            ['field' => 'ProgramarProd', 'label' => 'Day Scheduling', 'dateType' => 'date'],
            ['field' => 'NoProduccion', 'label' => 'Orden Prod.', 'dateType' => null],
            ['field' => 'Programado', 'label' => 'INN', 'dateType' => 'date'],
            ['field' => 'FlogsId', 'label' => 'Id Flog', 'dateType' => null],
            ['field' => 'CategoriaCalidad', 'label' => 'Cat. Calidad', 'dateType' => null],
            ['field' => 'NombreProyecto', 'label' => 'Descrip.', 'dateType' => null],
            ['field' => 'CustName', 'label' => 'Custname', 'dateType' => null],
            ['field' => 'AplicacionId', 'label' => 'Aplic.', 'dateType' => null],
            ['field' => 'Observaciones', 'label' => 'Obs', 'dateType' => null],
            ['field' => 'TipoPedido', 'label' => 'Tipo Ped.', 'dateType' => null],
            ['field' => 'NoTiras', 'label' => 'Tiras', 'dateType' => null],
            ['field' => 'Peine', 'label' => 'Pei.', 'dateType' => null],
            ['field' => 'LargoCrudo', 'label' => 'Lcr', 'dateType' => null],
            ['field' => 'PesoCrudo', 'label' => 'Pcr', 'dateType' => null],
            ['field' => 'Luchaje', 'label' => 'Luc', 'dateType' => null],
            ['field' => 'CalibreTrama2', 'label' => 'Calibre Tra', 'dateType' => null],
            ['field' => 'FibraTrama', 'label' => 'Fibra Trama', 'dateType' => null],
            ['field' => 'DobladilloId', 'label' => 'Dob', 'dateType' => null],
            ['field' => 'PasadasTrama', 'label' => 'Pasadas Tra', 'dateType' => null],
            ['field' => 'PasadasComb1', 'label' => 'Pasadas C1', 'dateType' => null],
            ['field' => 'PasadasComb2', 'label' => 'Pasadas C2', 'dateType' => null],
            ['field' => 'PasadasComb3', 'label' => 'Pasadas C3', 'dateType' => null],
            ['field' => 'PasadasComb4', 'label' => 'Pasadas C4', 'dateType' => null],
            ['field' => 'PasadasComb5', 'label' => 'Pasadas C5', 'dateType' => null],
            ['field' => 'AnchoToalla', 'label' => 'Ancho por Toalla', 'dateType' => null],
            ['field' => 'CodColorTrama', 'label' => 'Código Color Tra', 'dateType' => null],
            ['field' => 'ColorTrama', 'label' => 'Color Tra', 'dateType' => null],
            ['field' => 'CalibreComb1', 'label' => 'Calibre C1', 'dateType' => null],
            ['field' => 'FibraComb1', 'label' => 'Fibra C1', 'dateType' => null],
            ['field' => 'CodColorComb1', 'label' => 'Código Color C1', 'dateType' => null],
            ['field' => 'NombreCC1', 'label' => 'Color C1', 'dateType' => null],
            ['field' => 'CalibreComb2', 'label' => 'Calibre C2', 'dateType' => null],
            ['field' => 'FibraComb2', 'label' => 'Fibra C2', 'dateType' => null],
            ['field' => 'CodColorComb2', 'label' => 'Código Color C2', 'dateType' => null],
            ['field' => 'NombreCC2', 'label' => 'Color C2', 'dateType' => null],
            ['field' => 'CalibreComb3', 'label' => 'Calibre C3', 'dateType' => null],
            ['field' => 'FibraComb3', 'label' => 'Fibra C3', 'dateType' => null],
            ['field' => 'CodColorComb3', 'label' => 'Código Color C3', 'dateType' => null],
            ['field' => 'NombreCC3', 'label' => 'Color C3', 'dateType' => null],
            ['field' => 'CalibreComb4', 'label' => 'Calibre C4', 'dateType' => null],
            ['field' => 'FibraComb4', 'label' => 'Fibra C4', 'dateType' => null],
            ['field' => 'CodColorComb4', 'label' => 'Código Color C4', 'dateType' => null],
            ['field' => 'NombreCC4', 'label' => 'Color C4', 'dateType' => null],
            ['field' => 'CalibreComb5', 'label' => 'Calibre C5', 'dateType' => null],
            ['field' => 'FibraComb5', 'label' => 'Fibra C5', 'dateType' => null],
            ['field' => 'CodColorComb5', 'label' => 'Código Color C5', 'dateType' => null],
            ['field' => 'NombreCC5', 'label' => 'Color C5', 'dateType' => null],
            ['field' => 'MedidaPlano', 'label' => 'Plano', 'dateType' => null],
            ['field' => 'CuentaPie', 'label' => 'Cuenta Pie', 'dateType' => null],
            ['field' => 'CodColorCtaPie', 'label' => 'Código Color Pie', 'dateType' => null],
            ['field' => 'NombreCPie', 'label' => 'Color Pie', 'dateType' => null],
            ['field' => 'PesoGRM2', 'label' => 'Peso (gr/m²)', 'dateType' => null],
            ['field' => 'DiasEficiencia', 'label' => 'Días Ef.', 'dateType' => null],
            ['field' => 'ProdKgDia', 'label' => 'Prod (Kg)/Día', 'dateType' => null],
            ['field' => 'StdDia', 'label' => 'Std/Día', 'dateType' => null],
            ['field' => 'ProdKgDia2', 'label' => 'Prod (Kg)/Día 2', 'dateType' => null],
            ['field' => 'StdToaHra', 'label' => 'Std (Toa/Hr) 100%', 'dateType' => null],
            ['field' => 'DiasJornada', 'label' => 'Días Jornada', 'dateType' => null],
            ['field' => 'HorasProd', 'label' => 'Horas', 'dateType' => null],
            ['field' => 'StdHrsEfect', 'label' => 'Std/Hr Efectivo', 'dateType' => null],
            ['field' => 'FechaInicio', 'label' => 'Inicio', 'dateType' => 'datetime'],
            ['field' => 'FechaFinal', 'label' => 'Fin', 'dateType' => 'datetime'],
            ['field' => 'EntregaProduc', 'label' => 'Fecha Compromiso', 'dateType' => 'date'],
            ['field' => 'EntregaPT', 'label' => 'Fecha Compromiso', 'dateType' => 'date'],
            ['field' => 'EntregaCte', 'label' => 'Entrega', 'dateType' => 'datetime'],
            ['field' => 'PTvsCte', 'label' => 'Dif vs Compromiso', 'dateType' => null],

            // Karl Mayer. Jacquard y Smit no las usan: quedan vacías.
            // Mismo orden que el formulario de codificación. No son editables aquí.
            ['field' => 'CuentaBarra1', 'label' => 'Cuenta barra 1', 'dateType' => null],
            ['field' => 'CalibreBarra1', 'label' => 'Calibre barra 1', 'dateType' => null],
            ['field' => 'CodColorBarra1', 'label' => 'Cód. color barra 1', 'dateType' => null],
            ['field' => 'ColorBarra1', 'label' => 'Color barra 1', 'dateType' => null],
            ['field' => 'FibraBarra1', 'label' => 'Fibra barra 1', 'dateType' => null],
            ['field' => 'PasadasBarra1', 'label' => 'Pasadas barra 1', 'dateType' => null],
            ['field' => 'CuentaBarra2', 'label' => 'Cuenta barra 2', 'dateType' => null],
            ['field' => 'CalibreBarra2', 'label' => 'Calibre barra 2', 'dateType' => null],
            ['field' => 'CodColorBarra2', 'label' => 'Cód. color barra 2', 'dateType' => null],
            ['field' => 'ColorBarra2', 'label' => 'Color barra 2', 'dateType' => null],
            ['field' => 'FibraBarra2', 'label' => 'Fibra barra 2', 'dateType' => null],
            ['field' => 'PasadasBarra2', 'label' => 'Pasadas barra 2', 'dateType' => null],
            ['field' => 'CuentaBarra3', 'label' => 'Cuenta barra 3', 'dateType' => null],
            ['field' => 'CalibreBarra3', 'label' => 'Calibre barra 3', 'dateType' => null],
            ['field' => 'CodColorBarra3', 'label' => 'Cód. color barra 3', 'dateType' => null],
            ['field' => 'ColorBarra3', 'label' => 'Color barra 3', 'dateType' => null],
            ['field' => 'FibraBarra3', 'label' => 'Fibra barra 3', 'dateType' => null],
            ['field' => 'PasadasBarra3', 'label' => 'Pasadas barra 3', 'dateType' => null],
            ['field' => 'CuentaBarra4', 'label' => 'Cuenta barra 4', 'dateType' => null],
            ['field' => 'CalibreBarra4', 'label' => 'Calibre barra 4', 'dateType' => null],
            ['field' => 'CodColorBarra4', 'label' => 'Cód. color barra 4', 'dateType' => null],
            ['field' => 'ColorBarra4', 'label' => 'Color barra 4', 'dateType' => null],
            ['field' => 'FibraBarra4', 'label' => 'Fibra barra 4', 'dateType' => null],
            ['field' => 'PasadasBarra4', 'label' => 'Pasadas barra 4', 'dateType' => null],

        ];
    }
}
