<?php

namespace App\Models\catcodificados;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CatCodificados extends Model
{
    use HasFactory;

    protected $table = 'CatCodificados';
    // Sin primaryKey ya que la tabla no tiene campo Id
    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
        'NumOrden',
        'FechaOrden',
        'FechaCumplimiento',
        'Departamento',
        'TelarId',
        'Prioridad',
        'Modelo',
        'ClaveModelo',
        'Tamano',
        'InventSizeId',
        'Tolerancia',
        'CodigoDibujo',
        'FechaCompromiso',
        'FlogsId',
        'Clave',
        'Cantidad',
        'Peine',
        'Ancho',
        'Largo',
        'P_crudo',
        'Luchaje',
        'Tra',
        'Hilo',
        'CodColorTrama',
        'NombreColorTrama',
        'OBS_Trama',
        'Tipoplano',
        'Medplano',
        'TipoRizo',
        'AlturaRizo',
        'OBS',
        'VelocMinima',
        'Rizo',
        'Hilo_2',
        'Cuenta',
        'OBS_2',
        'Pie',
        'Hilo_3',
        'Cuenta_2',
        'OBS_3',
        'C1',
        'OBS_11',
        'C2',
        'OBS_12',
        'C3',
        'OBS_13',
        'C4',
        'OBS_14',
        'MedCenefa',
        'MedInicioRizoCenefa',
        'Razurada',
        'TIRAS',
        'RepeticionesP/corte',
        'NoMarbete',
        'CambioRepaso',
        'Vendedor',
        'NoOrden',
        'Observaciones',
        'TramaAnchoPeine',
        'LogLuchaTotal',
        'C1TramaFondo',
        'Hilo_4',
        'OBS_4',
        'PASADAS',
        'C1_2',
        'Hilo_5',
        'OBS_5',
        'CodColor',
        'NombreColor',
        'PASADAS_2',
        'C2_2',
        'Hilo_6',
        'OBS_6',
        'CodColor_2',
        'NombreColor_2',
        'PASADAS_3',
        'C3_2',
        'Hilo_7',
        'OBS_7',
        'CodColor_3',
        'NombreColor_3',
        'PASADAS_4',
        'C4_2',
        'Hilo_8',
        'OBS_8',
        'Cod Color_4',
        'NombreColor_4',
        'PASADAS_5',
        'C5',
        'Hilo_9',
        'OBS_9',
        'Cod Color_5',
        'NombreColor_5',
        'PASADAS_6',
        'TOTAL',
        'RespInicio',
        'HrInicio',
        'HrTermino',
        'MinutosCambio',
        'PesoMuestra',
        'RegAlinacion',
        'estecamponotienenombre1',
        'OBSParaPro',
        'CantidadProducir_2',
        'Tejidas',
        'pzaXrollo',
    ];

    protected $casts = [
        'FechaOrden' => 'date',
        'FechaCumplimiento' => 'date',
        'FechaCompromiso' => 'date',
        'TelarId' => 'integer',
        'Peine' => 'integer',
        'Ancho' => 'integer',
        'Largo' => 'integer',
        'VelocMinima' => 'integer',
        'Rizo' => 'float',
        'Hilo_2' => 'float',
        'Cuenta' => 'integer',
        'Pie' => 'float',
        'Hilo_3' => 'float',
        'Cuenta_2' => 'integer',
        'TIRAS' => 'integer',
        'NoMarbete' => 'float',
        'Hilo_5' => 'float',
        'Hilo_6' => 'float',
        'Hilo_7' => 'float',
        'Hilo_8' => 'float',
        'Hilo_9' => 'float',
    ];
}

