<?php

namespace App\Http\Controllers\Planeacion\ProgramaTejido\helper;

use App\Models\Planeacion\ReqProgramaTejido;
use App\Support\Planeacion\ProgramaTejido\ColumnasGrillaProgramaTejido;

class UtilityHelpers
{
    /** ponytail: adaptador temporal, retirar al migrar consumidores (usar ColumnasGrillaProgramaTejido::todas). */
    public static function getTableColumns(): array
    {
        return ColumnasGrillaProgramaTejido::todas();
    }

    public static function extractResumen(ReqProgramaTejido $r): array
    {
        return [
            'Id' => $r->Id,
            // Campos editables inline
            'TamanoClave' => $r->TamanoClave,
            'ItemId' => $r->ItemId,
            'InventSizeId' => $r->InventSizeId,
            'FlogsId' => $r->FlogsId,
            'NombreProducto' => $r->NombreProducto,
            'NombreProyecto' => $r->NombreProyecto,
            'CustName' => $r->CustName,
            'CalendarioId' => $r->CalendarioId,
            'AplicacionId' => $r->AplicacionId,
            'TipoPedido' => $r->TipoPedido,
            'Rasurado' => $r->Rasurado,
            'CambioHilo' => $r->CambioHilo,
            'Ancho' => $r->Ancho,
            'AnchoToalla' => $r->AnchoToalla,
            'EficienciaSTD' => $r->EficienciaSTD,
            'VelocidadSTD' => $r->VelocidadSTD,
            'FibraRizo' => $r->FibraRizo,
            'CuentaRizo' => $r->CuentaRizo,
            'CalibreRizo' => $r->CalibreRizo,
            'CalibreRizo2' => $r->CalibreRizo2,
            'CalibrePie' => $r->CalibrePie,
            'CalibrePie2' => $r->CalibrePie2,
            'CuentaPie' => $r->CuentaPie,
            'FibraPie' => $r->FibraPie,
            'TotalPedido' => $r->TotalPedido,
            'PedidoTempo' => $r->PedidoTempo,
            'SaldoPedido' => $r->SaldoPedido,
            'Produccion' => $r->Produccion,
            'Repeticiones' => $r->Repeticiones,
            'MtsRollo' => $r->MtsRollo,
            'PzasRollo' => $r->PzasRollo,
            'TotalRollos' => $r->TotalRollos,
            'TotalPzas' => $r->TotalPzas,
            'SaldoMarbete' => $r->SaldoMarbete,
            'NoMarbete' => $r->NoMarbete,
            'RollosProgramados' => $r->RollosProgramados,
            'FechaInicio' => $r->FechaInicio,
            'FechaFinal' => $r->FechaFinal,
            'EntregaProduc' => $r->EntregaProduc,
            'EntregaPT' => $r->EntregaPT,
            'EntregaCte' => $r->EntregaCte,
            'ProgramarProd' => $r->ProgramarProd,
            'PTvsCte' => $r->PTvsCte,
            'NoTiras' => $r->NoTiras,
            'Peine' => $r->Peine,
            'LargoCrudo' => $r->LargoCrudo,
            'Luchaje' => $r->Luchaje,
            'PesoCrudo' => $r->PesoCrudo,
            'PesoGRM2' => $r->PesoGRM2,
            'DiasEficiencia' => $r->DiasEficiencia,
            'ProdKgDia' => $r->ProdKgDia,
            'StdDia' => $r->StdDia,
            'ProdKgDia2' => $r->ProdKgDia2,
            'StdToaHra' => $r->StdToaHra,
            'DiasJornada' => $r->DiasJornada,
            'HorasProd' => $r->HorasProd,
            'StdHrsEfect' => $r->StdHrsEfect,
            'Observaciones' => $r->Observaciones,
            'PorcentajeSegundos' => $r->PorcentajeSegundos,
            'DobladilloId' => $r->DobladilloId,
            'MedidaPlano' => $r->MedidaPlano,
            'PasadasTrama' => $r->PasadasTrama,
            'CalibreTrama' => $r->CalibreTrama,
            'CalibreTrama2' => $r->CalibreTrama2,
            'FibraTrama' => $r->FibraTrama,
            'CodColorTrama' => $r->CodColorTrama,
            'ColorTrama' => $r->ColorTrama,
            'PasadasComb1' => $r->PasadasComb1,
            'CalibreComb1' => $r->CalibreComb1,
            'CalibreComb12' => $r->CalibreComb12,
            'FibraComb1' => $r->FibraComb1,
            'CodColorComb1' => $r->CodColorComb1,
            'NombreCC1' => $r->NombreCC1,
            'PasadasComb2' => $r->PasadasComb2,
            'CalibreComb2' => $r->CalibreComb2,
            'CalibreComb22' => $r->CalibreComb22,
            'FibraComb2' => $r->FibraComb2,
            'CodColorComb2' => $r->CodColorComb2,
            'NombreCC2' => $r->NombreCC2,
            'PasadasComb3' => $r->PasadasComb3,
            'CalibreComb3' => $r->CalibreComb3,
            'CalibreComb32' => $r->CalibreComb32,
            'FibraComb3' => $r->FibraComb3,
            'CodColorComb3' => $r->CodColorComb3,
            'NombreCC3' => $r->NombreCC3,
            'PasadasComb4' => $r->PasadasComb4,
            'CalibreComb4' => $r->CalibreComb4,
            'CalibreComb42' => $r->CalibreComb42,
            'FibraComb4' => $r->FibraComb4,
            'CodColorComb4' => $r->CodColorComb4,
            'NombreCC4' => $r->NombreCC4,
            'PasadasComb5' => $r->PasadasComb5,
            'CalibreComb5' => $r->CalibreComb5,
            'CalibreComb52' => $r->CalibreComb52,
            'FibraComb5' => $r->FibraComb5,
            'CodColorComb5' => $r->CodColorComb5,
            'NombreCC5' => $r->NombreCC5,
        ];
    }
}
