<?php

namespace App\Models\Planeacion;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ReqModelosCodificados extends Model
{
    use HasFactory;

    protected $table = 'ReqModelosCodificados';
    protected $primaryKey = 'Id';
    public $incrementing = true;
    protected $keyType = 'int';
    public $timestamps = false;

    protected $fillable = [
        'Id',
        'TamanoClave',
        'OrdenTejido',
        'FechaTejido',
        'FechaCumplimiento',
        'SalonTejidoId',
        'NoTelarId',
        'Prioridad',
        'Nombre',
        'ClaveModelo',
        'ItemId',
        'InventSizeId',
        'Tolerancia',
        'CodigoDibujo',
        'FechaCompromiso',
        'FlogsId',
        'NombreProyecto',
        'Clave',
        'Pedido',
        'Peine',
        'AnchoToalla',
        'LargoToalla',
        'PesoCrudo',
        'Luchaje',
        'CalibreTrama',
        'CalibreTrama2',
        'CodColorTrama',
        'ColorTrama',
        'FibraId',
        'DobladilloId',
        'MedidaPlano',
        'TipoRizo',
        'AlturaRizo',
        'Obs',
        'VelocidadSTD',
        'CalibreRizo',
        'CalibreRizo2',
        'CuentaRizo',
        'FibraRizo',
        'CalibrePie',
        'CalibrePie2',
        'CuentaPie',
        'FibraPie',
        'Comb1',
        'Obs1',
        'Comb2',
        'Obs2',
        'Comb3',
        'Obs3',
        'Comb4',
        'Obs4',
        'MedidaCenefa',
        'MedIniRizoCenefa',
        'Rasurado',
        'NoTiras',
        'Repeticiones',
        'TotalMarbetes',
        'CambioRepaso',
        'Vendedor',
        'CatCalidad',
        'Obs5',
        'AnchoPeineTrama',
        'LogLuchaTotal',
        'CalTramaFondoC1',
        'CalTramaFondoC12',
        'FibraTramaFondoC1',
        'PasadasTramaFondoC1',
        'CalibreComb1',
        'CalibreComb12',
        'FibraComb1',
        'CodColorC1',
        'NomColorC1',
        'PasadasComb1',
        'CalibreComb2',
        'CalibreComb22',
        'FibraComb2',
        'CodColorC2',
        'NomColorC2',
        'PasadasComb2',
        'CalibreComb3',
        'CalibreComb32',
        'FibraComb3',
        'CodColorC3',
        'NomColorC3',
        'PasadasComb3',
        'CalibreComb4',
        'CalibreComb42',
        'FibraComb4',
        'CodColorC4',
        'NomColorC4',
        'PasadasComb4',
        'CalibreComb5',
        'CalibreComb52',
        'FibraComb5',
        'CodColorC5',
        'NomColorC5',
        'PasadasComb5',
        'Total',
        'PasadasDibujo',
        'Contraccion',
        'TramasCMTejido',
        'ContracRizo',
        'ClasificacionKG',
        'KGDia',
        'Densidad',
        'PzasDiaPasadas',
        'PzasDiaFormula',
        'DIF',
        'EFIC',
        'Rev',
        'TIRAS',
        'PASADAS',
        'ColumCT',
        'ColumCU',
        'ColumCV',
        'ComprobarModDup',
        'OrdPrincipal'
    ];

    // Castings para conversión de tipos al guardar en BD
    protected $casts = [
        // INT fields (deben ser enteros)
        'Peine' => 'integer',
        'AnchoToalla' => 'integer',
        'LargoToalla' => 'integer',
        'PesoCrudo' => 'integer',
        'Luchaje' => 'integer',
        'MedidaPlano' => 'integer',
        'VelocidadSTD' => 'integer',
        'NoTiras' => 'integer',
        'Repeticiones' => 'integer',
        'TotalMarbetes' => 'integer',
        'AnchoPeineTrama' => 'integer',
        'LogLuchaTotal' => 'integer',
        'ColumCT' => 'integer',
        'ColumCU' => 'integer',
        'ColumCV' => 'integer',
        'TIRAS' => 'integer',
        'OrdPrincipal' => 'integer', // INT NULL en SQL Server

        // DECIMAL fields (deben ser float/double)
        'CalibreTrama' => 'float',
        'CalibreTrama2' => 'float',
        'CalibreRizo' => 'float',
        'CalibreRizo2' => 'float',
        'CalibrePie' => 'float',
        'CalibrePie2' => 'float',
        'Total' => 'float',
        'KGDia' => 'float',
        'Densidad' => 'float',
        'PzasDiaPasadas' => 'float',
        'PzasDiaFormula' => 'float',
        'DIF' => 'float',
        'EFIC' => 'float',
        'Rev' => 'float',
        'PASADAS' => 'float',

        // Dates
        'FechaTejido' => 'datetime:Y-m-d H:i:s',
        'FechaCumplimiento' => 'datetime:Y-m-d H:i:s',
        'FechaCompromiso' => 'datetime:Y-m-d H:i:s',
    ];
}
