<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Modelos extends Model
{
    use HasFactory;

    protected $table = 'modelos';

    public $timestamps = false;

    protected $fillable = [
        'CONCATENA',
        'RASEMA',
        'Fecha_Orden',
        'Fecha_Cumplimiento',
        'Departamento',
        'Telar_Actual',
        'Prioridad',
        'Modelo',
        'CLAVE_MODELO',
        'CLAVE_AX',
        'Tamanio_AX',
        'TOLERANCIA',
        'CODIGO_DE_DIBUJO',
        'Fecha_Compromiso',
        'Nombre_de_Formato_Logistico',
        'Clave',
        'Cantidad_a_Producir',
        'Peine',
        'Ancho',
        'Largo',
        'P_crudo',
        'Luchaje',
        'Tra',
        'Hilo',
        'OBS',
        'Tipo_plano',
        'Med_plano',
        'TIPO_DE_RIZO',
        'ALTURA_DE_RIZO',
        'OBS_1',
        'Veloc_Minima',
        'Rizo',
        'Hilo_1',
        'CUENTA',
        'OBS_2',
        'Pie',
        'Hilo_2',
        'CUENTA1',
        'OBS_3',
        'C1',
        'OBS_4',
        'C2',
        'OBS_5',
        'C3',
        'OBS_6',
        'C4',
        'OBS_7',
        'Med_de_Cenefa',
        'Med_de_inicio_de_rizo_a_cenefa',
        'RAZURADA',
        'TIRAS',
        'Repeticiones_p_corte',
        'No_De_Marbetes',
        'Cambio_de_repaso',
        'Vendedor',
        'No_Orden',
        'Observaciones',
        'TRAMA_Ancho_Peine',
        'LOG_DE_LUCHA_TOTAL',
        'C1_Trama_de_Fondo',
        'Hilo_A_1',
        'OBS_A_1',
        'PASADAS_1',
        'C1_A_1',
        'Hilo_A_2',
        'OBS_A_2',
        'PASADAS_2',
        'C2_A_2',
        'Hilo_A_3',
        'OBS_A_3',
        'PASADAS_3',
        'C3_A_3',
        'Hilo_A_4',
        'OBS_A_4',
        'PASADAS_4',
        'C4_A_4',
        'Hilo_A_5',
        'OBS_A_5',
        'PASADAS_5',
        'C5_A_5',
        'Hilo_A_6',
        'OBS_A_6',
        'X',
        'TOTAL',
        'PASADAS_DIBUJO',
        'Contraccion',
        'Tramas_cm_Tejido',
        'Contrac_Rizo',
        'Clasificación(KG)',
        'KG_p_dia',
        'Densidad',
        'Pzas_p_dia_pasadas',
        'Pzas_p_dia_formula',
        'DIF',
        'EFIC',
        'Rev',
        'TIRAS_2',
        'PASADAS',
        'CU',
        'CV',
        'CW',
        'COMPROBAR_modelos_duplicados',
    ];
}
