<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ReqModelosCodificados extends Model
{
    use HasFactory;

    protected $table = 'ReqModelosCodificados';
    protected $primaryKey = 'Id';
    public $timestamps = false;

    protected $fillable = [
        'TamanoClave',
        'OrdenTejido',
        'FechaTejido',
        'FechaCumplimiento',
        'SalonTejidoId',
        'NoTelarId',
        'Prioridad',
        'Nombre',
        'ClaveModelo',
        'ItemId',
        'InventSizeId',
        'Tolerancia',
        'CodigoDibujo',
        'FechaCompromiso',
        'FlogsId',
        'NombreProyecto',
        'Clave',
        'Pedido',
        'Peine',
        'AnchoToalla',
        'LargoToalla',
        'PesoCrudo',
        'Luchaje',
        'CalibreTrama',
        'CalibreTrama2',
        'CodColorTrama',
        'ColorTrama',
        'FibraId',
        'DobladilloId',
        'MedidaPlano',
        'TipoRizo',
        'AlturaRizo',
        'Obs',
        'VelocidadSTD',
        'CalibreRizo',
        'CalibreRizo2',
        'CuentaRizo',
        'FibraRizo',
        'CalibrePie',
        'CalibrePie2',
        'CuentaPie',
        'FibraPie',
        'Comb1',
        'Obs1',
        'Comb2',
        'Obs2',
        'Comb3',
        'Obs3',
        'Comb4',
        'Obs4',
        'MedidaCenefa',
        'MedIniRizoCenefa',
        'Rasurado',
        'NoTiras',
        'Repeticiones',
        'TotalMarbetes',
        'CambioRepaso',
        'Vendedor',
        'CatCalidad',
        'Obs5',
        'AnchoPeineTrama',
        'LogLuchaTotal',
        'CalTramaFondoC1',
        'CalTramaFondoC12',
        'FibraTramaFondoC1',
        'PasadasTramaFondoC1',
        'CalibreComb1',
        'CalibreComb12',
        'FibraComb1',
        'CodColorC1',
        'NomColorC1',
        'PasadasComb1',
        'CalibreComb2',
        'CalibreComb22',
        'FibraComb2',
        'CodColorC2',
        'NomColorC2',
        'PasadasComb2',
        'CalibreComb3',
        'CalibreComb32',
        'FibraComb3',
        'CodColorC3',
        'NomColorC3',
        'PasadasComb3',
        'CalibreComb4',
        'CalibreComb42',
        'FibraComb4',
        'CodColorC4',
        'NomColorC4',
        'PasadasComb4',
        'CalibreComb5',
        'CalibreComb52',
        'FibraComb5',
        'CodColorC5',
        'NomColorC5',
        'PasadasComb5',
        'Total',
        'PasadasDibujo',
        'Contraccion',
        'TramasCMTejido',
        'ContracRizo',
        'ClasificacionKG',
        'KGDia',
        'Densidad',
        'PzasDiaPasadas',
        'PzasDiaFormula',
        'DIF',
        'EFIC',
        'Rev',
        'TIRAS',
        'PASADAS',
        'ColumCT',
        'ColumCU',
        'ColumCV',
        'ComprobarModDup'
    ];

    // Si quieres manejar fechas como Carbon sin alterar texto cuando venga vacío,
    // puedes usar $dates; si alguna llega como cadena no válida, Eloquent la deja igual.
    protected $dates = [
        'FechaTejido',
        'FechaCumplimiento',
        'FechaCompromiso',
    ];

    // ¡Sin casts ni accessors! Para no añadir .0000 ni convertir literales en null/0.
}
